<h3>This new page is generated by CRM/Firstextension/Page/Meetings.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}The current time in my local community now is %1.{/ts}</p>
{* This is the email of the desired contact*}
<p>The total number of registered contacts is: {$contactGotten}</p>
 {$contacts|@var_dump}
